<a href="https://colab.research.google.com/github/muhammadrafique92/Assignment/blob/main/Numpy_assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np;

In [3]:
print(np.__version__)

2.1.3


**Q1:** Create and Reshape. Create a 1-D NumPy array containing the numbers 1 to 12, then reshape it into a 3 × 4
2-D array. Print the reshaped array and its shape. [5]
• Case 1: Input 1 to 12 → Output shape (3, 4)
• Case 2: Input 1 to 8, reshape into 2 × 4 → Output shape (2, 4)

In [2]:
arr1 = np.arange(1, 13)
reshaped_arr1=arr1.reshape(3, 4)
print("arr1:", arr1)
print("reshaped_arr1:", reshaped_arr1)
print("shape case1:",reshaped_arr1.shape)
print("-" * 30)

arr2 = np.arange(1, 9)
reshaped_arr2=arr2.reshape(2, 4)
print("arr2:", arr2)
print("reshaped_arr2:", reshaped_arr2)
print("shape case2:",reshaped_arr2.shape)

arr1: [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped_arr1: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape case1: (3, 4)
------------------------------
arr2: [1 2 3 4 5 6 7 8]
reshaped_arr2: [[1 2 3 4]
 [5 6 7 8]]
shape case2: (2, 4)


**Q2:** Filter Even Numbers. Given a NumPy array of integers, use boolean filtering (no loops) to return only the
even numbers. [5]
• Case 1: Input [1, 2, 3, 4, 5, 6, 7, 8] → Output [2 4 6 8]
• Case 2: Input [10, 15, 20, 25, 30] → Output [10 20 30]

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
E1=arr[arr % 2 == 0]
print("C1-Even_numbers:", E1)
print("-" * 27)

arr = np.array([10, 15, 20, 25, 30])
E2=arr[arr % 2 == 0]
print("C2-Even_numbers:", E2)

C1-Even_numbers: [2 4 6 8]
---------------------------
C2-Even_numbers: [10 20 30]


**Q3:** Row and Column Sums of a 2-D Array. Given a 2-D array, compute the sum of each row and the sum of
each column using np.sum() with the axis parameter. [5]
• Case 1: Input [[1, 2, 3], [4, 5, 6]]
→ Row sums: [6 15], Col sums: [5 7 9]
• Case 2: Input [[1, 1], [2, 2], [3, 3]]
→ Row sums: [2 4 6], Col sums: [6 6]

In [4]:
arr1= np.array([[1, 2, 3], [4, 5, 6]])
arr2= np.array([[1, 1], [2, 2], [3, 3]])
R1_sum = np.sum(arr1, axis=1)
C1_sum = np.sum(arr1, axis=0)
R2_sum = np.sum(arr2, axis=1)
C2_sum = np.sum(arr2, axis=0)
print("Row sums:", R1_sum, "Column sums:", C1_sum)
print("-" * 40)
print("Row sums:", R2_sum, "Column sums:", C2_sum)

Row sums: [ 6 15] Column sums: [5 7 9]
----------------------------------------
Row sums: [2 4 6] Column sums: [6 6]


**Q4:** Normalize an Array. Given a NumPy array of numbers, normalize it so all values fall between 0 and 1 using
the formula

x − min(x)/
max(x) − min(x)
.

• Case 1: Input [10, 20, 30, 40, 50]
→ Output [0. 0.25 0.5 0.75 1.]
• Case 2: Input [0, 5, 10]
→ Output [0. 0.5 1.]

In [5]:
x1= np.array([10,20,30,40,50])
x2= np.array([0,5,10])
Nor_Arr1 = (x1-min(x1))/(max(x1)-min(x1))
Nor_Arr2 = (x2-min(x2))/(max(x2)-min(x2))
print("C1-Normalized array:", Nor_Arr1)
print("-"*45)
print("C2-Normalized array:", Nor_Arr2)

C1-Normalized array: [0.   0.25 0.5  0.75 1.  ]
---------------------------------------------
C2-Normalized array: [0.  0.5 1. ]


**Q5:** Replace Values Using np.where(). Given an array of exam scores, use np.where() to replace every score
below 50 with “Fail” and every score 50 or above with “Pass”. The resulting array will be a string array.
• Case 1: Input [45, 60, 30, 90]
→ Output [

′F ail′ ′P ass′ ′F ail′ ′P ass′
]

• Case 2: Input [70, 40, 50]
→ Output [

′P ass′ ′F ail′ ′P ass′
]

In [6]:
arr1= np.array([45, 60, 30, 90])
arr2= np.array([70, 40, 50])
score1= np.where(arr1<50,'Fail','Pass')
score2= np.where(arr2<50,'Fail','Pass')
print(score1,'\n','-'*28,'\n',score2)

['Fail' 'Pass' 'Fail' 'Pass'] 
 ---------------------------- 
 ['Pass' 'Fail' 'Pass']


**Q6:** Matrix Addition and Multiplication. Given two 2 × 2 matrices, compute their element-wise sum and their
matrix product using the @ operator.

In [7]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
sum= A+B
product= A@B
print('sum:',sum)
print('product:',product)
print('-'*20)
A = np.array([[1, 0],[0, 1]])
B = np.array([[2, 3],[4, 5]])
sum= A+B
product= A@B
print('sum:',sum)
print('product:',product)


sum: [[ 6  8]
 [10 12]]
product: [[19 22]
 [43 50]]
--------------------
sum: [[3 3]
 [4 6]]
product: [[2 3]
 [4 5]]


**Q7:** Find Indices of the Maximum and Minimum. Given a NumPy array, find the index of the maximum value
and the index of the minimum value using np.argmax() and np.argmin().

In [16]:
arr1= np.array([3, 7, 1, 9, 4]);
print('Max index:',np.argmax(arr1),'Min index:',np.argmin(arr1),'\n','-'*25)
arr2= np.array([10, 2, 8]);
print('Max index:',np.argmax(arr2),'Min index:',np.argmin(arr2))

Max index: 3 Min index: 2 
 -------------------------
Max index: 0 Min index: 1


**Q8:** Stack Two Arrays Vertically and Horizontally. Given two 1-D arrays of equal length, stack them both
vertically using vstack() and horizontally using hstack(). Print both results.

In [27]:
arr= np.array([[1, 2, 3], [4, 5, 6]]);
print('vstack:', np.vstack(arr),'hstack:', np.hstack(arr),'\n','-'*30)
A= np.array([0, 0])
B= np.array([1, 1])
print('vstack:', np.vstack((A,B)),'\n','hstack:', np.hstack((A,B)))

vstack: [[1 2 3]
 [4 5 6]] hstack: [1 2 3 4 5 6] 
 ------------------------------
vstack: [[0 0]
 [1 1]] 
 hstack: [0 0 1 1]


**Q9:** Compute Statistics on a Dataset. Given a NumPy array representing daily temperatures, compute and print
the mean, median, standard deviation, minimum, and maximum.

In [35]:
A= np.array([20, 22, 19, 25, 21])
print("Mean:", np.mean(A), "Median:", np.median(A), "Std:", round(np.std(A), 3), "Min:", np.min(A), "Max:", np.max(A))
print('-'*50)
B= np.array([30, 32, 31, 29])
print("Mean:", np.mean(B), "Median:", np.median(B), "Std:", round(np.std(B), 3), "Min:", np.min(B), "Max:", np.max(B))


Mean: 21.4 Median: 21.0 Std: 2.059 Min: 19 Max: 25
--------------------------------------------------
Mean: 30.5 Median: 30.5 Std: 1.118 Min: 29 Max: 32


**Q10:** Split an Array into Equal Chunks. Given a 1-D array, split it into 3 equal (or as equal as possible) parts
using np.array_split(), and print each part.

In [42]:
A= np.array([1, 2, 3, 4, 5, 6])
B= np.array([1, 2, 3, 4, 5, 6, 7])
print(np.array_split(A,3),'\n','-'*50,'\n',np.array_split(B,3))

[array([1, 2]), array([3, 4]), array([5, 6])] 
 -------------------------------------------------- 
 [array([1, 2, 3]), array([4, 5]), array([6, 7])]
